#ifndef CARP_INSTRUCTIONS_H
#define CARP_INSTRUCTIONS_H

/* make instruction numbers easier on the eyes */
typedef enum {
  CARP_INSTR_UNDEF = -1,
  CARP_INSTR_HALT ,
  CARP_INSTR_NOP  ,
  CARP_INSTR_LOADR,
  CARP_INSTR_LOAD ,
  CARP_INSTR_STORE,
  CARP_INSTR_MOV  ,
  CARP_INSTR_ADD  ,
  CARP_INSTR_SUB  ,
  CARP_INSTR_MUL  ,
  CARP_INSTR_MOD  ,
  CARP_INSTR_SHR  ,
  CARP_INSTR_SHL  ,
  CARP_INSTR_NOT  ,
  CARP_INSTR_XOR  ,
  CARP_INSTR_OR   ,
  CARP_INSTR_AND  ,
  CARP_INSTR_INCR ,
  CARP_INSTR_DECR ,
  CARP_INSTR_INC  ,
  CARP_INSTR_DEC  ,
  CARP_INSTR_PUSHR,
  CARP_INSTR_PUSH ,
  CARP_INSTR_POP  ,
  CARP_INSTR_CMP  ,
  CARP_INSTR_LT   ,
  CARP_INSTR_GT   ,
  CARP_INSTR_JZ   ,
  CARP_INSTR_RJZ  ,
  CARP_INSTR_JNZ  ,
  CARP_INSTR_RJNZ ,
  CARP_INSTR_JMP  ,
  CARP_INSTR_RJMP ,
  CARP_INSTR_CALL ,
  CARP_INSTR_RET  ,
  CARP_INSTR_PREG ,
  CARP_INSTR_PTOP ,
  CARP_NUM_INSTRS,
} carp_instr;

extern char carp_reverse_instr[][6];

#endif
